apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/argocd`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: argocd-stripprefix
          namespace: argocd
    - kind: Rule
      match: PathPrefix(`/argocd`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
      middlewares:
        - name: argocd-stripprefix
          namespace: argocd
  tls:
    certResolver: default
