apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jenkins
            port: 
              name: http
    host: jenkins.alie.javeriana.edu.co
